# -*-codeing = utf-8 -*-
# @Author: wzq
# @Description:
# @FileName：
# -*- coding: utf-8 -*-
# Description: Full-Map Inference and Earthquake-Colored Overlay Mapping

import os
import numpy as np
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm
from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap, BoundaryNorm
from scipy.ndimage import sobel, median_filter

from model import SeismicStarSSM
from train import SeismicDataset


def predict_and_plot(model, dataset, raw_data_path, num_clusters=4):
    device = next(model.parameters()).device
    model.eval()

    dataloader = DataLoader(dataset, batch_size=512, shuffle=False, num_workers=10)

    H, W = 1767, 576
    facies_map = np.zeros((H, W), dtype=np.int32) - 1

    print(">>> Predicting Facies Map...")
    with torch.no_grad():
        for x_i, x_t, x_c, pos in tqdm(dataloader):
            x_i, x_t, x_c = x_i.to(device), x_t.to(device), x_c.to(device)
            q = model(x_i, x_t, x_c)
            labels = q.argmax(dim=1).cpu().numpy()

            il = pos['center_il'].numpy()
            xl = pos['center_xl'].numpy()
            facies_map[il, xl] = labels

    unique, counts = np.unique(facies_map, return_counts=True)
    sorted_indices = np.argsort(-counts)
    map_dict = {old_label: new_label for new_label, old_label in enumerate(sorted_indices)}
    remapped_map = np.vectorize(map_dict.get)(facies_map)

    remapped_map = median_filter(remapped_map, size=5)

    print(">>> 6. Generating Background Overlay...")
    try:
        raw_data = np.memmap(raw_data_path, dtype='float32', mode='r', shape=(W, H, 10))
        sobel_sim = raw_data[:, :, 9]
        v_min, v_max = np.percentile(sobel_sim, 2), np.percentile(sobel_sim, 98)
        sobel_sim_clipped = np.clip(sobel_sim, v_min, v_max)

        # 线性映射到 0~1 区间：0 代表强边界，1 代表连续平滑地层
        background = (sobel_sim_clipped - v_min) / (v_max - v_min + 1e-8)

    except Exception as e:
        print(f"Error loading background: {e}")
        background = np.ones((H, W))

    print(">>> 7. Plotting Final Image...")
    plt.figure(figsize=(18, 10))

    # 画前景分类结果 (彩色)
    paper_colors = [
        '#BF7F7F',
        '#797DD4',
        '#E3C38D',
        '#A9E0DD'
    ]
    cmap_facies = ListedColormap(paper_colors)
    bounds = np.arange(num_clusters + 1) - 0.5
    norm = BoundaryNorm(bounds, cmap_facies.N)

    plt.imshow(facies_map.T, cmap=cmap_facies, norm=norm, aspect='auto', interpolation='nearest')

    # 2. 【核心大招】：创建专用的“边界描边蒙版”
    from matplotlib.colors import LinearSegmentedColormap
    # 0（低相似度/边界）映射为 85% 浓郁的纯黑色，1（高相似度/平滑）映射为完全透明(alpha=0)！
    black_to_transparent = LinearSegmentedColormap.from_list("black_alpha", [(0, 0, 0, 0.85), (0, 0, 0, 0)])

    plt.imshow(background, cmap=black_to_transparent, aspect='auto', interpolation='bicubic', vmin=0, vmax=1.0)

    plt.title("End-to-End Deep Clustering Seismic Facies")
    save_path = "/root/autodl-tmp/paper_overlay_ETE_Augmenter.png"
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f">>> Saved successfully to {save_path}")


if __name__ == "__main__":
    config = {
        "data_root": "../model_Predata/combined_3d_by_axis",
        "raw_data_path": "../model_Predata/combined_3d_by_axis/axis_2/slice_0010.dat",
        "model_path": "/root/autodl-tmp/model_DEC_final.pth",  # Weights generated by train.py
        "seed": 42,
        "num_clusters": 4
    }

    torch.manual_seed(config["seed"])
    np.random.seed(config["seed"])
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    print(">>> Phase 2: Full Map Inference and Plotting")
    model = SeismicStarSSM(embed_dim=128, num_clusters=config["num_clusters"]).to(device)

    if os.path.exists(config["model_path"]):
        model.load_state_dict(torch.load(config["model_path"], map_location=device))
        print(f">>> Loaded trained weights from {config['model_path']}")
    else:
        print(f"Warning: {config['model_path']} not found! Ensure train.py has been run successfully.")

    infer_ds = SeismicDataset(config["data_root"], sampling_interval=1)
    predict_and_plot(model, infer_ds, config["raw_data_path"], num_clusters=config["num_clusters"])